# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class InferenceServiceStub(object):
    """Ingest -> Inference : push frames, no detections returned to ingest (forward flow)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.grpcStreamFrames = channel.stream_unary(
                '/inference.InferenceService/grpcStreamFrames',
                request_serializer=services__pb2.grpcFrameRequest.SerializeToString,
                response_deserializer=services__pb2.grpcAck.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Ingest -> Inference : push frames, no detections returned to ingest (forward flow)
    """

    def grpcStreamFrames(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'grpcStreamFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.grpcStreamFrames,
                    request_deserializer=services__pb2.grpcFrameRequest.FromString,
                    response_serializer=services__pb2.grpcAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Ingest -> Inference : push frames, no detections returned to ingest (forward flow)
    """

    @staticmethod
    def grpcStreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/inference.InferenceService/grpcStreamFrames',
            services__pb2.grpcFrameRequest.SerializeToString,
            services__pb2.grpcAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrackingServiceStub(object):
    """Inference -> Tracking : push detections forward; tracking fills in gTrackId
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.grpcStreamDetections = channel.stream_unary(
                '/inference.TrackingService/grpcStreamDetections',
                request_serializer=services__pb2.grpcDetectionResponse.SerializeToString,
                response_deserializer=services__pb2.grpcAck.FromString,
                _registered_method=True)


class TrackingServiceServicer(object):
    """Inference -> Tracking : push detections forward; tracking fills in gTrackId
    """

    def grpcStreamDetections(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'grpcStreamDetections': grpc.stream_unary_rpc_method_handler(
                    servicer.grpcStreamDetections,
                    request_deserializer=services__pb2.grpcDetectionResponse.FromString,
                    response_serializer=services__pb2.grpcAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.TrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Inference -> Tracking : push detections forward; tracking fills in gTrackId
    """

    @staticmethod
    def grpcStreamDetections(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/inference.TrackingService/grpcStreamDetections',
            services__pb2.grpcDetectionResponse.SerializeToString,
            services__pb2.grpcAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IngestAdminStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCamera = channel.unary_unary(
                '/inference.IngestAdmin/AddCamera',
                request_serializer=services__pb2.ingestCamera.SerializeToString,
                response_deserializer=services__pb2.ingestAdminReply.FromString,
                _registered_method=True)
        self.StartStream = channel.unary_unary(
                '/inference.IngestAdmin/StartStream',
                request_serializer=services__pb2.ingestStreamId.SerializeToString,
                response_deserializer=services__pb2.ingestAdminReply.FromString,
                _registered_method=True)
        self.StopStream = channel.unary_unary(
                '/inference.IngestAdmin/StopStream',
                request_serializer=services__pb2.ingestStreamId.SerializeToString,
                response_deserializer=services__pb2.ingestAdminReply.FromString,
                _registered_method=True)
        self.RemoveCamera = channel.unary_unary(
                '/inference.IngestAdmin/RemoveCamera',
                request_serializer=services__pb2.ingestStreamId.SerializeToString,
                response_deserializer=services__pb2.ingestAdminReply.FromString,
                _registered_method=True)
        self.ListCameras = channel.unary_unary(
                '/inference.IngestAdmin/ListCameras',
                request_serializer=services__pb2.ingestEmpty.SerializeToString,
                response_deserializer=services__pb2.ingestCameraList.FromString,
                _registered_method=True)


class IngestAdminServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddCamera(self, request, context):
        """register + start a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStream(self, request, context):
        """(re)start a known, stopped stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """stop one stream, leave the rest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCamera(self, request, context):
        """stop + forget
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCameras(self, request, context):
        """status of all known cameras
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCamera,
                    request_deserializer=services__pb2.ingestCamera.FromString,
                    response_serializer=services__pb2.ingestAdminReply.SerializeToString,
            ),
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=services__pb2.ingestStreamId.FromString,
                    response_serializer=services__pb2.ingestAdminReply.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=services__pb2.ingestStreamId.FromString,
                    response_serializer=services__pb2.ingestAdminReply.SerializeToString,
            ),
            'RemoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCamera,
                    request_deserializer=services__pb2.ingestStreamId.FromString,
                    response_serializer=services__pb2.ingestAdminReply.SerializeToString,
            ),
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=services__pb2.ingestEmpty.FromString,
                    response_serializer=services__pb2.ingestCameraList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.IngestAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.IngestAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestAdmin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.IngestAdmin/AddCamera',
            services__pb2.ingestCamera.SerializeToString,
            services__pb2.ingestAdminReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.IngestAdmin/StartStream',
            services__pb2.ingestStreamId.SerializeToString,
            services__pb2.ingestAdminReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.IngestAdmin/StopStream',
            services__pb2.ingestStreamId.SerializeToString,
            services__pb2.ingestAdminReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.IngestAdmin/RemoveCamera',
            services__pb2.ingestStreamId.SerializeToString,
            services__pb2.ingestAdminReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inference.IngestAdmin/ListCameras',
            services__pb2.ingestEmpty.SerializeToString,
            services__pb2.ingestCameraList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
